MyLibraryRuby/MyLibrary/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :books

  root 'books#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

MyLibraryRuby/MyLibrary/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MyLibraryRuby/MyLibrary/app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
end

MyLibraryRuby/MyLibrary/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

MyLibraryRuby/MyLibrary/app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all
    end
    
    def new
        @book = Book.new
    end

    def edit
        @book = Book.find(params[:id])
    end

    def create
        @book = Book.new(book_params)

        if @book.save
            redirect_to @book
        else
            render 'new'
        end
    end

    def update
        @book = Book.find(params[:id])

        if @book.update(book_params)
            redirect_to @book
        else
            render 'edit'
        end
    end

    def show
        @book = Book.find(params[:id])
    end

    def destroy
        @book = Book.find(params[:id])
        @book.destroy

        redirect_to books_path
    end

    private 
        def book_params
            params.require(:book).permit(:title, :content)
        end
end

MyLibraryRuby/MyLibrary/app/helpers/application_helper.rb
module ApplicationHelper
end

MyLibraryRuby/MyLibrary/app/helpers/books_helper.rb
module BooksHelper
end

MyLibraryRuby/MyLibrary/app/helpers/welcome_helper.rb
module WelcomeHelper
end

MyLibraryRuby/MyLibrary/app/views/books/edit.html.erb
<h1>Edit Book</h1>
 
<%= form_with(model: @book, local: true) do |form| %>
 
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@bood.errors.count, "error") %> prohibited
        this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group">
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title, :class => "form-control" %>
    </p>
  </div>
 
  <div class="form-group">
    <p>
      <%= form.label :content %><br>
      <%= form.text_area :content, :class => "form-control" %>
    </p>
  </div>
 
  <p>
    <%= form.submit :class => "btn btn-primary" %>
  </p>
 
<% end %>

MyLibraryRuby/MyLibrary/app/views/books/index.html.erb
<h1>My Books</h1>

<% @books.each do |book| %>
    <div class="container">
      <h3><%= book.title %></h3>
      <p><%= link_to 'Read', book_path(book), :class => "btn btn-default" %></p>
        <hr>
    </div>
<% end %>

MyLibraryRuby/MyLibrary/app/views/books/new.html.erb
<h1>New Book</h1>

<%= form_with scope: :book, url: books_path, local: true do |form| %>
    
    <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@book.errors.count, "error") %> prohibited
        this book from being saved:
      </h2>
      <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    
  <div class="form-group">
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title, :class => "form-control" %>
    </p>
  </div>
    

  <div class="form-group">
   
    <p>
      <%= form.label :content%><br>
      <%= form.text_area :content, :class => "form-control" %>
    </p>

  </div>
   
    <p>
      <%= form.submit :class => "btn btn-primary" %>
    </p>
  <% end %>

MyLibraryRuby/MyLibrary/app/views/books/show.html.erb
<div class="container my-5">
<br>
<br>
<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @book.content %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %>
<%= link_to 'Delete', book_path(@book),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>

</div>

MyLibraryRuby/MyLibrary/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyLibrary</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" type="text/css" href="/app/assets/stylesheets/bootstrap/rails-bootstrap">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to 'My Library', "/", :class => "navbar-brand" %>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><%= link_to 'Home', "/" %></li>
                    <li><%= link_to 'Add a New Book', new_book_path() %></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content py-5">
      <%= yield %>
        <hr />
    </div>
</body>
</html>